name: Release on Tag

on:
  push:
    tags:
      - '*.*.*'  # Trigger release job on version tag push

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[docs]  # Assumes your pyproject.toml defines an "extras" group for docs

      - name: Generate API Docs
        run: sphinx-apidoc -o docs/api/ mast_contributor_tools mast_contributor_tools/tests/*

      - name: Build documentation
        run: make -C docs html

      - name: Upload Documentation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/_build/html

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
